### ISSUE TITLE
Setup email client (Heroku and Sendgrid)

### ISSUE THREAD

**Issue by JoshuaVSherman** [WebJamApps/break-point-back#2]
- [x] need to upgrade Heroku to include credit card information
- [x] https://account.postmarkapp.com/sign_up

**Comment by JoshuaVSherman** [comment]
@BreakPointMinistries send message over slack to setup a screensharing session

**Comment by BreakPointMinistries** [comment]
If you would like me to set it up with my cc info, just shoot me a message on slack to tell me where to go.
